apiVersion: v1
kind: Service
metadata:
  name: product-catalog
  namespace: default
spec:
  type: {{ .Values.service.type }}
  selector:
    app: product-catalog
  ports: 
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 5000
    nodePort: {{ .Values.service.nodePort }}
